version: "3.9"

services:
  web:
    build: .
    ports:
      - "10000:10000"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      - API_HOST=0.0.0.0
      - API_PORT=10000
    depends_on:
      - db
    networks:
      - app_network
    command: >
      bash -c "
        echo 'Esperando o banco de dados estar pronto...';
        while ! nc -z -v -w30 db 5432; do sleep 1; done;
        alembic upgrade head && 
        uvicorn app.main:app --host 0.0.0.0 --port 10000 --reload
      "

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

volumes:
  postgres_data:
    driver: local

networks:
  app_network:
    driver: bridge
