"""Adiciona margem_lucro a produto

Revision ID: 199eb314f851
Revises: 75c00b9d7d1e
Create Date: 2025-04-03 08:41:14.850320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '199eb314f851'
down_revision: Union[str, None] = '75c00b9d7d1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produto', sa.Column('margem_lucro', sa.Numeric(5, 2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produto', 'margem_lucro')
    # ### end Alembic commands ###
