"""adicionando avaliacoes

Revision ID: 75c00b9d7d1e
Revises: c28b7017a5cd
Create Date: 2025-04-02 21:24:52.042276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '75c00b9d7d1e'
down_revision: Union[str, None] = 'c28b7017a5cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avaliacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nota', sa.Float(), nullable=False),
    sa.Column('comentario', sa.String(length=500), nullable=True),
    sa.Column('criado_em', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('atualizado_em', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_avaliacao_id'), 'avaliacao', ['id'], unique=False)
    op.add_column('cupom', sa.Column('criado_em', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.add_column('cupom', sa.Column('ativo', sa.Boolean(), nullable=True))
    op.add_column('endereco', sa.Column('complemento', sa.String(length=100), nullable=True))
    op.add_column('endereco', sa.Column('bairro', sa.String(length=100), nullable=False))
    op.add_column('endereco', sa.Column('atualizado_em', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('endereco', 'numero',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('endereco', 'estado',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=2),
               existing_nullable=False)
    op.alter_column('endereco', 'cep',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=9),
               existing_nullable=False)
    op.drop_constraint('endereco_usuario_id_fkey', 'endereco', type_='foreignkey')
    op.create_foreign_key(None, 'endereco', 'usuario', ['usuario_id'], ['id'], ondelete='CASCADE')
    op.alter_column('pagamento', 'valor',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
    op.drop_constraint('pagamento_venda_id_fkey', 'pagamento', type_='foreignkey')
    op.create_foreign_key(None, 'pagamento', 'venda', ['venda_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('produto_categoria_id_fkey', 'produto', type_='foreignkey')
    op.create_foreign_key(None, 'produto', 'categorias', ['categoria_id'], ['id'], ondelete='SET NULL')
    op.add_column('usuario', sa.Column('atualizado_em', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('usuario', 'senha',
               existing_type=sa.VARCHAR(length=60),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('usuario', 'criado_em',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('venda', 'total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('venda', 'data_venda',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('venda_cupom_id_fkey', 'venda', type_='foreignkey')
    op.drop_constraint('venda_endereco_id_fkey', 'venda', type_='foreignkey')
    op.create_foreign_key(None, 'venda', 'endereco', ['endereco_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'venda', 'cupom', ['cupom_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'venda', type_='foreignkey')
    op.drop_constraint(None, 'venda', type_='foreignkey')
    op.create_foreign_key('venda_endereco_id_fkey', 'venda', 'endereco', ['endereco_id'], ['id'])
    op.create_foreign_key('venda_cupom_id_fkey', 'venda', 'cupom', ['cupom_id'], ['id'])
    op.alter_column('venda', 'data_venda',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('venda', 'total',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('usuario', 'criado_em',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('usuario', 'senha',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=60),
               existing_nullable=False)
    op.drop_column('usuario', 'atualizado_em')
    op.drop_constraint(None, 'produto', type_='foreignkey')
    op.create_foreign_key('produto_categoria_id_fkey', 'produto', 'categorias', ['categoria_id'], ['id'])
    op.drop_constraint(None, 'pagamento', type_='foreignkey')
    op.create_foreign_key('pagamento_venda_id_fkey', 'pagamento', 'venda', ['venda_id'], ['id'])
    op.alter_column('pagamento', 'valor',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_constraint(None, 'endereco', type_='foreignkey')
    op.create_foreign_key('endereco_usuario_id_fkey', 'endereco', 'usuario', ['usuario_id'], ['id'])
    op.alter_column('endereco', 'cep',
               existing_type=sa.String(length=9),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('endereco', 'estado',
               existing_type=sa.String(length=2),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('endereco', 'numero',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.drop_column('endereco', 'atualizado_em')
    op.drop_column('endereco', 'bairro')
    op.drop_column('endereco', 'complemento')
    op.drop_column('cupom', 'ativo')
    op.drop_column('cupom', 'criado_em')
    op.drop_index(op.f('ix_avaliacao_id'), table_name='avaliacao')
    op.drop_table('avaliacao')
    # ### end Alembic commands ###
