"""initial migration

Revision ID: 8d3540db3c64
Revises: 
Create Date: 2025-04-29 09:22:47.033552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d3540db3c64'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('imagem_url', sa.String(length=255), nullable=True),
    sa.Column('cor_destaque', sa.String(length=7), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.Column('meta_title', sa.String(length=100), nullable=True),
    sa.Column('meta_description', sa.String(length=255), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_categorias_id'), 'categorias', ['id'], unique=False)
    op.create_table('cupom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('desconto', sa.Float(), nullable=False),
    sa.Column('validade', sa.TIMESTAMP(), nullable=False),
    sa.Column('criado_em', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_index(op.f('ix_cupom_id'), 'cupom', ['id'], unique=False)
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('cpf_cnpj', sa.String(length=20), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('tipo_usuario', sa.Enum('CLIENTE', 'ADMIN', 'FUNCIONARIO', 'ENTREGADOR', name='tipousuarioenum', native_enum=False), nullable=False),
    sa.Column('refresh_token', sa.String(length=500), nullable=True),
    sa.Column('criado_em', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuario_cpf_cnpj'), 'usuario', ['cpf_cnpj'], unique=True)
    op.create_index(op.f('ix_usuario_email'), 'usuario', ['email'], unique=True)
    op.create_index(op.f('ix_usuario_id'), 'usuario', ['id'], unique=False)
    op.create_table('carrinho',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_finalizado', sa.Boolean(), nullable=True),
    sa.Column('data_finalizacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carrinho_id'), 'carrinho', ['id'], unique=False)
    op.create_table('cartao_salvo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('bandeira', sa.String(length=50), nullable=False),
    sa.Column('ultimos_digitos', sa.String(length=4), nullable=False),
    sa.Column('nome_impresso', sa.String(length=100), nullable=True),
    sa.Column('validade_mes', sa.Integer(), nullable=True),
    sa.Column('validade_ano', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cartao_salvo_id'), 'cartao_salvo', ['id'], unique=False)
    op.create_table('categoria_imagem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('imagem_url', sa.String(length=500), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categoria_imagem_id'), 'categoria_imagem', ['id'], unique=False)
    op.create_table('endereco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('logradouro', sa.String(length=255), nullable=False),
    sa.Column('numero', sa.String(length=10), nullable=False),
    sa.Column('complemento', sa.String(length=100), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=False),
    sa.Column('cidade', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.String(length=2), nullable=False),
    sa.Column('cep', sa.String(length=9), nullable=False),
    sa.Column('criado_em', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_endereco_id'), 'endereco', ['id'], unique=False)
    op.create_table('entregador_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('placa', sa.String(length=10), nullable=True),
    sa.Column('cnh', sa.String(length=20), nullable=True),
    sa.Column('endereco', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_table('produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('preco', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('unidade_medida', sa.String(length=10), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('margem_lucro', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('preco_final', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produto_id'), 'produto', ['id'], unique=False)
    op.create_index(op.f('ix_produto_sku'), 'produto', ['sku'], unique=True)
    op.create_table('avaliacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nota', sa.Float(), nullable=False),
    sa.Column('comentario', sa.String(length=500), nullable=True),
    sa.Column('criado_em', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('atualizado_em', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_avaliacao_id'), 'avaliacao', ['id'], unique=False)
    op.create_table('estoque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estoque_id'), 'estoque', ['id'], unique=False)
    op.create_table('item_carrinho',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('carrinho_id', sa.Integer(), nullable=True),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('valor_unitario', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('valor_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['carrinho_id'], ['carrinho.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_carrinho_id'), 'item_carrinho', ['id'], unique=False)
    op.create_table('lista_desejos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'produto_id', name='uix_usuario_produto')
    )
    op.create_index(op.f('ix_lista_desejos_id'), 'lista_desejos', ['id'], unique=False)
    op.create_index(op.f('ix_lista_desejos_produto_id'), 'lista_desejos', ['produto_id'], unique=False)
    op.create_index(op.f('ix_lista_desejos_usuario_id'), 'lista_desejos', ['usuario_id'], unique=False)
    op.create_table('produto_destaque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('posicao', sa.Integer(), nullable=True, comment='Ordem de exibição no destaque'),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('tipo_destaque', sa.String(length=20), nullable=True, comment="Tipos: 'principal', 'secundario', 'promocional', 'novidade', 'oferta'"),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('produto_id')
    )
    op.create_index(op.f('ix_produto_destaque_id'), 'produto_destaque', ['id'], unique=False)
    op.create_table('produto_imagem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('imagem_url', sa.String(length=500), nullable=False),
    sa.Column('tipo', sa.Enum('DESTAQUE', 'GALERIA', 'THUMBNAIL', 'ZOOM', name='tipoimagemproduto'), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.Column('visivel', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_produto_id_ordem', 'produto_imagem', ['produto_id', 'ordem'], unique=False)
    op.create_index(op.f('ix_produto_imagem_id'), 'produto_imagem', ['id'], unique=False)
    op.create_table('promocao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('desconto_percentual', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('preco_promocional', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('data_inicio', sa.TIMESTAMP(), nullable=False),
    sa.Column('data_fim', sa.TIMESTAMP(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('data_fim > data_inicio', name='check_datas_promocao'),
    sa.CheckConstraint('desconto_percentual >= 0 AND desconto_percentual <= 100', name='check_desconto'),
    sa.CheckConstraint('preco_promocional IS NULL OR preco_promocional > 0', name='check_preco_promocional'),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promocao_id'), 'promocao', ['id'], unique=False)
    op.create_index(op.f('ix_promocao_produto_id'), 'promocao', ['produto_id'], unique=False)
    op.create_table('venda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('endereco_id', sa.Integer(), nullable=True),
    sa.Column('cupom_id', sa.Integer(), nullable=True),
    sa.Column('carrinho_id', sa.Integer(), nullable=True),
    sa.Column('total', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('valor_total_bruto', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('valor_desconto', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('tipo_desconto', sa.Enum('NENHUM', 'CUPOM', 'PROMOCAO', name='tipodescontoenum', create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'PAGO', 'CANCELADO', name='status_venda_enum', create_constraint=True), nullable=False),
    sa.Column('status_pagamento', sa.Enum('PENDENTE', 'EM_ANALISE', 'APROVADO', 'RECUSADO', 'CANCELADO', 'ESTORNADO', name='status_pagamento_enum', create_constraint=True), nullable=False),
    sa.Column('data_venda', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['carrinho_id'], ['carrinho.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cupom_id'], ['cupom.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['endereco_id'], ['endereco.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_venda_id'), 'venda', ['id'], unique=False)
    op.create_table('entrega',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venda_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'A_CAMINHO', 'ENTREGUE', name='statusentregaenum'), nullable=False),
    sa.Column('criado_em', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('entregador_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['entregador_id'], ['usuario.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['venda_id'], ['venda.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entrega_id'), 'entrega', ['id'], unique=False)
    op.create_table('item_venda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venda_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_unitario', sa.Float(), nullable=False),
    sa.Column('criado_em', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.ForeignKeyConstraint(['venda_id'], ['venda.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_venda_id'), 'item_venda', ['id'], unique=False)
    op.create_table('movimentacao_estoque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venda_id', sa.Integer(), nullable=True),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('tipo_movimentacao', sa.Enum('ENTRADA', 'SAIDA', name='tipomovimentoenum'), nullable=False),
    sa.Column('data', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('criado_em', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.ForeignKeyConstraint(['venda_id'], ['venda.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimentacao_estoque_id'), 'movimentacao_estoque', ['id'], unique=False)
    op.create_table('pagamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venda_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'EM_ANALISE', 'APROVADO', 'RECUSADO', 'CANCELADO', 'ESTORNADO', name='statuspagamento'), nullable=False),
    sa.Column('metodo_pagamento', sa.Enum('PIX', 'CARTAO_CREDITO', 'CARTAO_DEBITO', 'BOLETO', 'CARTEIRA_DIGITAL', name='metodopagamentoenum'), nullable=False),
    sa.Column('transacao_id', sa.String(length=100), nullable=True),
    sa.Column('numero_parcelas', sa.Integer(), nullable=True),
    sa.Column('bandeira_cartao', sa.String(length=50), nullable=True),
    sa.Column('ultimos_digitos_cartao', sa.String(length=4), nullable=True),
    sa.Column('nome_cartao', sa.String(length=100), nullable=True),
    sa.Column('codigo_pix', sa.String(length=300), nullable=True),
    sa.Column('linha_digitavel_boleto', sa.String(length=300), nullable=True),
    sa.Column('criado_em', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['venda_id'], ['venda.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pagamento_id'), 'pagamento', ['id'], unique=False)
    op.create_table('entrega_candidato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entrega_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('data_interesse', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.Enum('pendente', 'aceita', 'recusada', name='statusentregacandidato'), nullable=False),
    sa.ForeignKeyConstraint(['entrega_id'], ['entrega.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entrega_candidato_id'), 'entrega_candidato', ['id'], unique=False)
    op.create_table('historico_pagamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pagamento_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'AUTORIZADO', 'FALHOU', 'CANCELADO', 'ESTORNADO', name='statushistoricopagamento'), nullable=False),
    sa.Column('metodo_pagamento', sa.String(length=50), nullable=True),
    sa.Column('observacao', sa.String(length=255), nullable=True),
    sa.Column('data_evento', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pagamento_id'], ['pagamento.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historico_pagamento_id'), 'historico_pagamento', ['id'], unique=False)
    op.create_table('rastreamento_entrega',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entrega_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('atualizado_em', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entrega_id'], ['entrega.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rastreamento_entrega_entrega_id'), 'rastreamento_entrega', ['entrega_id'], unique=False)
    op.create_index(op.f('ix_rastreamento_entrega_id'), 'rastreamento_entrega', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rastreamento_entrega_id'), table_name='rastreamento_entrega')
    op.drop_index(op.f('ix_rastreamento_entrega_entrega_id'), table_name='rastreamento_entrega')
    op.drop_table('rastreamento_entrega')
    op.drop_index(op.f('ix_historico_pagamento_id'), table_name='historico_pagamento')
    op.drop_table('historico_pagamento')
    op.drop_index(op.f('ix_entrega_candidato_id'), table_name='entrega_candidato')
    op.drop_table('entrega_candidato')
    op.drop_index(op.f('ix_pagamento_id'), table_name='pagamento')
    op.drop_table('pagamento')
    op.drop_index(op.f('ix_movimentacao_estoque_id'), table_name='movimentacao_estoque')
    op.drop_table('movimentacao_estoque')
    op.drop_index(op.f('ix_item_venda_id'), table_name='item_venda')
    op.drop_table('item_venda')
    op.drop_index(op.f('ix_entrega_id'), table_name='entrega')
    op.drop_table('entrega')
    op.drop_index(op.f('ix_venda_id'), table_name='venda')
    op.drop_table('venda')
    op.drop_index(op.f('ix_promocao_produto_id'), table_name='promocao')
    op.drop_index(op.f('ix_promocao_id'), table_name='promocao')
    op.drop_table('promocao')
    op.drop_index(op.f('ix_produto_imagem_id'), table_name='produto_imagem')
    op.drop_index('ix_produto_id_ordem', table_name='produto_imagem')
    op.drop_table('produto_imagem')
    op.drop_index(op.f('ix_produto_destaque_id'), table_name='produto_destaque')
    op.drop_table('produto_destaque')
    op.drop_index(op.f('ix_lista_desejos_usuario_id'), table_name='lista_desejos')
    op.drop_index(op.f('ix_lista_desejos_produto_id'), table_name='lista_desejos')
    op.drop_index(op.f('ix_lista_desejos_id'), table_name='lista_desejos')
    op.drop_table('lista_desejos')
    op.drop_index(op.f('ix_item_carrinho_id'), table_name='item_carrinho')
    op.drop_table('item_carrinho')
    op.drop_index(op.f('ix_estoque_id'), table_name='estoque')
    op.drop_table('estoque')
    op.drop_index(op.f('ix_avaliacao_id'), table_name='avaliacao')
    op.drop_table('avaliacao')
    op.drop_index(op.f('ix_produto_sku'), table_name='produto')
    op.drop_index(op.f('ix_produto_id'), table_name='produto')
    op.drop_table('produto')
    op.drop_table('entregador_info')
    op.drop_index(op.f('ix_endereco_id'), table_name='endereco')
    op.drop_table('endereco')
    op.drop_index(op.f('ix_categoria_imagem_id'), table_name='categoria_imagem')
    op.drop_table('categoria_imagem')
    op.drop_index(op.f('ix_cartao_salvo_id'), table_name='cartao_salvo')
    op.drop_table('cartao_salvo')
    op.drop_index(op.f('ix_carrinho_id'), table_name='carrinho')
    op.drop_table('carrinho')
    op.drop_index(op.f('ix_usuario_id'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_email'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_cpf_cnpj'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_index(op.f('ix_cupom_id'), table_name='cupom')
    op.drop_table('cupom')
    op.drop_index(op.f('ix_categorias_id'), table_name='categorias')
    op.drop_table('categorias')
    # ### end Alembic commands ###
