"""criação de todas das tabelas iniciais

Revision ID: f5587af985fb
Revises: 
Create Date: 2025-04-02 09:59:09.616562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5587af985fb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_categoria_id'), 'categoria', ['id'], unique=False)
    op.create_table('cupom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('desconto', sa.Float(), nullable=False),
    sa.Column('validade', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_index(op.f('ix_cupom_id'), 'cupom', ['id'], unique=False)
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha', sa.String(length=60), nullable=False),
    sa.Column('cpf_cnpj', sa.String(length=20), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('tipo_usuario', sa.Enum('CLIENTE', 'ADMIN', 'FUNCIONARIO', 'ENTREGADOR', name='tipousuarioenum'), nullable=False),
    sa.Column('criado_em', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf_cnpj')
    )
    op.create_index(op.f('ix_usuario_email'), 'usuario', ['email'], unique=True)
    op.create_index(op.f('ix_usuario_id'), 'usuario', ['id'], unique=False)
    op.create_table('endereco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('logradouro', sa.String(length=255), nullable=False),
    sa.Column('numero', sa.String(length=10), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('cep', sa.String(length=20), nullable=False),
    sa.Column('criado_em', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_endereco_id'), 'endereco', ['id'], unique=False)
    op.create_table('produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produto_id'), 'produto', ['id'], unique=False)
    op.create_table('estoque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estoque_id'), 'estoque', ['id'], unique=False)
    op.create_table('movimentacao_estoque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('tipo_movimentacao', sa.Enum('ENTRADA', 'SAIDA', name='tipomovimentacao'), nullable=False),
    sa.Column('data', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('criado_em', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimentacao_estoque_id'), 'movimentacao_estoque', ['id'], unique=False)
    op.create_table('produto_imagem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('imagem_url', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produto_imagem_id'), 'produto_imagem', ['id'], unique=False)
    op.create_table('promocao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('desconto', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('data_inicio', sa.TIMESTAMP(), nullable=False),
    sa.Column('data_fim', sa.TIMESTAMP(), nullable=False),
    sa.Column('criado_em', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('desconto >= 0 AND desconto <= 100', name='check_desconto'),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promocao_id'), 'promocao', ['id'], unique=False)
    op.create_index(op.f('ix_promocao_produto_id'), 'promocao', ['produto_id'], unique=False)
    op.create_table('venda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('endereco_id', sa.Integer(), nullable=True),
    sa.Column('cupom_id', sa.Integer(), nullable=True),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'PAGO', 'CANCELADO', name='statusvendaenum'), nullable=False),
    sa.Column('data_venda', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cupom_id'], ['cupom.id'], ),
    sa.ForeignKeyConstraint(['endereco_id'], ['endereco.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_venda_id'), 'venda', ['id'], unique=False)
    op.create_table('entrega',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venda_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'A_CAMINHO', 'ENTREGUE', name='statusentregaenum'), nullable=False),
    sa.Column('criado_em', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['venda_id'], ['venda.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entrega_id'), 'entrega', ['id'], unique=False)
    op.create_table('item_venda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venda_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_unitario', sa.Float(), nullable=False),
    sa.Column('criado_em', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.ForeignKeyConstraint(['venda_id'], ['venda.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_venda_id'), 'item_venda', ['id'], unique=False)
    op.create_table('pagamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venda_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'APROVADO', 'CANCELADO', name='statuspagamento'), nullable=False),
    sa.Column('criado_em', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['venda_id'], ['venda.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pagamento_id'), 'pagamento', ['id'], unique=False)
    op.create_table('rastreamento_entrega',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entrega_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('atualizado_em', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entrega_id'], ['entrega.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rastreamento_entrega_entrega_id'), 'rastreamento_entrega', ['entrega_id'], unique=False)
    op.create_index(op.f('ix_rastreamento_entrega_id'), 'rastreamento_entrega', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rastreamento_entrega_id'), table_name='rastreamento_entrega')
    op.drop_index(op.f('ix_rastreamento_entrega_entrega_id'), table_name='rastreamento_entrega')
    op.drop_table('rastreamento_entrega')
    op.drop_index(op.f('ix_pagamento_id'), table_name='pagamento')
    op.drop_table('pagamento')
    op.drop_index(op.f('ix_item_venda_id'), table_name='item_venda')
    op.drop_table('item_venda')
    op.drop_index(op.f('ix_entrega_id'), table_name='entrega')
    op.drop_table('entrega')
    op.drop_index(op.f('ix_venda_id'), table_name='venda')
    op.drop_table('venda')
    op.drop_index(op.f('ix_promocao_produto_id'), table_name='promocao')
    op.drop_index(op.f('ix_promocao_id'), table_name='promocao')
    op.drop_table('promocao')
    op.drop_index(op.f('ix_produto_imagem_id'), table_name='produto_imagem')
    op.drop_table('produto_imagem')
    op.drop_index(op.f('ix_movimentacao_estoque_id'), table_name='movimentacao_estoque')
    op.drop_table('movimentacao_estoque')
    op.drop_index(op.f('ix_estoque_id'), table_name='estoque')
    op.drop_table('estoque')
    op.drop_index(op.f('ix_produto_id'), table_name='produto')
    op.drop_table('produto')
    op.drop_index(op.f('ix_endereco_id'), table_name='endereco')
    op.drop_table('endereco')
    op.drop_index(op.f('ix_usuario_id'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_email'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_index(op.f('ix_cupom_id'), table_name='cupom')
    op.drop_table('cupom')
    op.drop_index(op.f('ix_categoria_id'), table_name='categoria')
    op.drop_table('categoria')
    # ### end Alembic commands ###
